apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd  # Namespace dimana ArgoCD Anda terinstall
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 51.4.0  # Anda bisa memeriksa versi terbaru di repo helm
    helm:
      values: |
        grafana:
          adminPassword: prom-operator  # Ubah dengan password yang aman
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx-public  # Sesuaikan dengan ingress class yang Anda gunakan
            hosts:
              - grafana.test.my.id  # Ganti dengan domain Anda
        prometheus:
          prometheusSpec:
            retention: 10d
            resources:
              requests:
                cpu: 200m
                memory: 200Mi
              limits:
                cpu: 1000m
                memory: 1Gi
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx-public
            hosts:
              - prometheus.test.my.id  # Ganti dengan domain Anda
        alertmanager:
          alertmanagerSpec:
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                cpu: 500m
                memory: 500Mi
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx-public
            hosts:
              - alertmanager.test.my.id  # Ganti dengan domain Anda
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring  # Namespace untuk monitoring stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true